### ISSUE TITLE
Question: How to determine the sign position of planets, etc.?

### ISSUE THREAD

**Issue by kingram6865** [aloistr/swisseph#3]
The code is really fast.
My test code retrieved the position of the Sun:
```
{
longitude: 77.2707032514088,
latitude: 0.00017030973477109325,
distance: 1.0150754072616814,
longitudeSpeed: 0.9562904992667407,
latitudeSpeed: -0.000018033602508116673,
distanceSpeed: 0.00011533146435347834,
rflag: 258
}
```

- So how do I have the calculations return the Sign position of the planet?
- In this instance Sun is in Gemini, but the ephemeris does not return such data?
- Is there an API function I have overlooked?
- Is that sign(constellation) data something that is not provided by Swiss Ephemeris?
- Do I need to have the constellation boundaries already and calculate the sign by checking the planet's intersection in the zodia?

**Comment by toddcarnes** [comment]
You have to do that yourself.

Here's what I do.

```
// simple function to convert degrees to signs
const char* get_sign(double deg)
{
  static char* signs[] = { "ERR", "ARI", "TAU", "GEM", "CAN", "LEO", "VIR",
                           "LIB", "SCO", "SAG", "CAP", "AQU", "PIS" };

  // complain if we're not in range 0 - 360
  if (deg < 0 || deg >= 360) {return signs[0];}

  // determine what sign we are in
  if (deg < 30)  {return signs[1];}
  if (deg < 60)  {return signs[2];}
  if (deg < 90)  {return signs[3];}
  if (deg < 120) {return signs[4];}
  if (deg < 150) {return signs[5];}
  if (deg < 180) {return signs[6];}
  if (deg < 210) {return signs[7];}
  if (deg < 240) {return signs[8];}
  if (deg < 270) {return signs[9];}
  if (deg < 300) {return signs[10];}
  if (deg < 330) {return signs[11];}
  else           {return signs[12];}
}
```

**Comment by aloistr** [comment]
Please use the swiss ephemeris mailing list for all further questions.

**Comment by kingram6865** [comment]
> You have to do that yourself.
> 
> Here's what I do.
> 
> ```
> // simple function to convert degrees to signs
> const char* get_sign(double deg)
> {
>   static char* signs[] = { "ERR", "ARI", "TAU", "GEM", "CAN", "LEO", "VIR",
>                            "LIB", "SCO", "SAG", "CAP", "AQU", "PIS" };
> 
>   // complain if we're not in range 0 - 360
>   if (deg < 0 || deg >= 360) {return signs[0];}
> 
>   // determine what sign we are in
>   if (deg < 30)  {return signs[1];}
>   if (deg < 60)  {return signs[2];}
>   if (deg < 90)  {return signs[3];}
>   if (deg < 120) {return signs[4];}
>   if (deg < 150) {return signs[5];}
>   if (deg < 180) {return signs[6];}
>   if (deg < 210) {return signs[7];}
>   if (deg < 240) {return signs[8];}
>   if (deg < 270) {return signs[9];}
>   if (deg < 300) {return signs[10];}
>   if (deg < 330) {return signs[11];}
>   else           {return signs[12];}
> }
> ```

Thank you. 

I realized I would have to do it manually just before seeing your response.
I had not considered the error check. That's a good touch.

Further questions I will go to the mailing list.
